name: Build

on: [push, pull_request]
#on:
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
#    release:
#      types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            arch: x64
            vcpkg_triplet: "x64-windows"
          - os: windows-latest
            arch: x86
            vcpkg_triplet: "x86-windows"

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Linux & macOS
      - name: Build wheels (linux & macos)
        uses: pypa/cibuildwheel@v2.11.4
        if: runner.os != 'Windows'
        env:
          CIBW_SKIP: "cp36* pp* *i686 *musllinux*"
          CIBW_BEFORE_BUILD: "bash {package}/.github/workflows/before_build.sh ${{ matrix.os }}"
          CIBW_BEFORE_TEST: "cp -r {project}/tests .."
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "SDL_AUDIODRIVER=dummy pytest {project}/../tests"

      # Windows (vcpkg)
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      #- uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        if: runner.os == 'Windows'
        id: runvcpkg
        with:
          #vcpkgJsonGlob: 'vcpkg.json'
          #vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2 #2022.11.14

      - name: Build wheels (windows)
        uses: pypa/cibuildwheel@v2.11.2
        if: runner.os == 'Windows'
        env:
          CIBW_SKIP: "cp36* pp**"
          CIBW_BEFORE_BUILD: "bash {package}/.github/workflows/before_build.sh ${{ matrix.os }}"
          CIBW_BEFORE_TEST: "cp -r {project}/tests .."
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "SDL_AUDIODRIVER=dummy pytest {project}/../tests"
          VCPKG_BUILD: 1
          VCPKG_TOOLCHAIN: "${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
          VCPKG_DEFAULT_TRIPLET: "${{ env.VCPKG_DEFAULT_TRIPLET }}"

  #    - uses: actions/upload-artifact@v3
  #      with:
  #        path: ./wheelhouse/*.whl
  #        name: wheels_${{ matrix.os }}

  #build_sdist:
  #  name: Build source distribution
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3

  #    - name: Build sdist
  #      run: pipx run build --sdist

  #    - uses: actions/upload-artifact@v3
  #      with:
  #        path: dist/*.tar.gz
  #        name: mixstream-sdist.tar.gz

  vcpkg_export:
    name: Build Windows dependencies
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            vcpkg_triplet: "x64-windows"
          - arch: x86
            vcpkg_triplet: "x86-windows"

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet }}

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          #vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2 #2022.11.14
          #runVcpkgInstall: true
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet }}
          VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg/

      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "

      - name: Export vcpkg ports
        run: |
          ${{ github.workspace }}\vcpkg\vcpkg install --triplet ${{ matrix.vcpkg_triplet }} libvorbis portmidi sdl2-mixer soundtouch
          ${{ github.workspace }}\vcpkg\vcpkg export --nuget --zip glib libvorbis portmidi sdl2-mixer soundtouch

      - name: Upload vcpkg installed
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg_${{ matrix.arch }}
          path: vcpkg-export*
